version: 2
build:
    os: ubuntu-24.04
    tools:
        python: "miniforge3-25.11"
    jobs:
        pre_build:
            - python doc/generate_data_and_plots.py
python:
    install:
        - method: pip
          path: .
conda:
    environment: doc/readthedocs-env.yml
sphinx:
  configuration: doc/source/conf.py
