[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "p4"
version = "0.0.1"
requires-python = ">=3.11"
description = "Probe the effective potential landscape around an analyte using HOOMD-blue."
readme = "readme.md"
license-files = ["LICENSE"]
authors = [
  { name = "Joseph Burkhart", email = "joaburkh@umich.edu" },
]
dependencies = [
    # Glotzer Group
    "gsd>=4.2.0",       # can remove with minor refactoring
    "coxeter>=0.10.0",  # core, but could be confined to plotting if I used hoomd for overlap checks
    "rowan>=1.3.2",     # core

    # Data
    "numpy>=2.3.5",     # core
    "scipy>=1.16.3",            # used only for point in polygon check (could remove if that functionality is implemented natively)

    # Plotting
    "plotly>=6.6.0",   # only needed for Field
]

[project.optional-dependencies]
docs = [
  "sphinx>9.0",
  "furo>2025",
  "numpydoc",
  "nbsphinx",
  "sphinx-copybutton",
]

[tool.conda-lock]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.conda-lock.dependencies]
hoomd = ">=5.0.0" # core

[tool.uv.extra-build-dependencies]
p4 = ["setuptools"]
